// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp7zjBeqpStuv1X6RwFEbu420BbTZeKQ8',
    appId: '1:341582374312:web:c629102eb50b95d705a99d',
    messagingSenderId: '341582374312',
    projectId: 'testing-rebel',
    authDomain: 'testing-rebel.firebaseapp.com',
    storageBucket: 'testing-rebel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKtdw2pqrU0lHVLl6jo7tIitULvtxnUs',
    appId: '1:341582374312:android:da0dfe21087b783c05a99d',
    messagingSenderId: '341582374312',
    projectId: 'testing-rebel',
    storageBucket: 'testing-rebel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_agj9g8HaoplCuntJsLalscA65RrBOA',
    appId: '1:341582374312:ios:84c78599b5f34b0f05a99d',
    messagingSenderId: '341582374312',
    projectId: 'testing-rebel',
    storageBucket: 'testing-rebel.appspot.com',
    iosBundleId: 'com.rebelbionics.bionicInterface',
  );

}